### ISSUE TITLE
hprose js 和 hprose html5 的区别是？

### ISSUE THREAD

**Issue by yolio2003** [hprose/hprose-js#9]
hprose node 是很好理解的 hprose js 和 html5 则很难区分了，能不能有个页面整体介绍下。最好是个表格，区分出特性，会特别清晰。

这个要求可能很过分，不过真的很想了解清楚，谢谢，麻烦了！

**Comment by andot** [comment]
https://github.com/hprose/hprose-js/wiki/JavaScript-%E7%89%88%E6%9C%AC%E7%9A%84%E5%8C%BA%E5%88%AB

**Comment by yolio2003** [comment]
太感谢了，学习了！
